version: '3.1'
services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
  db:
    image: postgres


networks:
  clutternet:
    driver: bridge    